version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  # certbot-etc:
  # certbot-var:
  web-root:

networks:
  app-network:
    driver: bridge
